config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    get 'message', to: 'greetings#random'
  end

  root 'root#index'
  get 'root/index'
  get 'greetings/random'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root 'root#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/controllers/api/greetings_controller.rb
class Api::GreetingsController < ApplicationController
  def random
    message = Greeting.where(id: rand(1..5))
    render json: { greetings: message }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def random
    @message = Greeting.find(rand(1..5))
    render json: @message
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/greetings/_form.html.erb
<%= form_with(model: greeting) do |form| %>
  <% if greeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
        <% greeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/greetings/_greeting.html.erb
<div id="<%= dom_id greeting %>">
  <p>
    <strong>Message:</strong>
    <%= greeting.message %>
  </p>

</div>

app/views/greetings/edit.html.erb
<h1>Editing greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Show this greeting", @greeting %> |
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Greetings</h1>

<div id="greetings">
  <% @greetings.each do |greeting| %>
    <%= render greeting %>
    <p>
      <%= link_to "Show this greeting", greeting %>
    </p>
  <% end %>
</div>

<%= link_to "New greeting", new_greeting_path %>

app/views/greetings/new.html.erb
<h1>New greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @greeting %>

<div>
  <%= link_to "Edit this greeting", edit_greeting_path(@greeting) %> |
  <%= link_to "Back to greetings", greetings_path %>

  <%= button_to "Destroy this greeting", @greeting, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorldWebpack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<div id="root"></div>